# Generated by Django 3.2.3 on 2021-06-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('numero_sala', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_nacionalidade', models.CharField(max_length=255)),
                ('continente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_profissao', models.CharField(max_length=255)),
                ('salario_medio', models.FloatField(default=0)),
                ('anos_experiencia', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.IntegerField(default=0)),
                ('numero', models.BigIntegerField(default=0)),
                ('temWhatsapp', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30, null=True)),
                ('idade', models.IntegerField(default=0)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=10)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.departamento')),
                ('nacionalidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.nacionalidade')),
                ('profissao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profissao')),
                ('telefones', models.ManyToManyField(to='app.Telefone')),
            ],
        ),
    ]
