# Generated by Django 3.2.3 on 2021-06-22 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeClassificacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='formaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeformaPagamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contasReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataExpectativa', models.DateField()),
                ('dataRecebimento', models.DateField(null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(null=True)),
                ('situacao', models.BooleanField(default=0)),
                ('classificacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.classificacao')),
                ('formaPagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.formapagamento')),
            ],
        ),
        migrations.CreateModel(
            name='contasPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataVencimento', models.DateField()),
                ('dataPagamento', models.DateField(null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(null=True)),
                ('situacao', models.BooleanField(default=0)),
                ('classificacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.classificacao')),
                ('formaPagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.formapagamento')),
            ],
        ),
    ]
